basePath: /api/handler
definitions:
  dto.DashboardCurrent:
    properties:
      cpuPercent:
        items:
          type: number
        type: array
      cpuTotal:
        type: integer
      cpuUsed:
        type: number
      cpuUsedPercent:
        type: number
      diskData:
        items:
          $ref: '#/definitions/dto.DiskInfo'
        type: array
      gpuData:
        items:
          $ref: '#/definitions/dto.GPUInfo'
        type: array
      ioCount:
        type: integer
      ioReadBytes:
        type: integer
      ioReadTime:
        type: integer
      ioWriteBytes:
        type: integer
      ioWriteTime:
        type: integer
      load1:
        type: number
      load5:
        type: number
      load15:
        type: number
      loadUsagePercent:
        type: number
      memoryAvailable:
        type: integer
      memoryTotal:
        type: integer
      memoryUsed:
        type: integer
      memoryUsedPercent:
        type: number
      netBytesRecv:
        type: integer
      netBytesSent:
        type: integer
      procs:
        type: integer
      shotTime:
        type: string
      swapMemoryAvailable:
        type: integer
      swapMemoryTotal:
        type: integer
      swapMemoryUsed:
        type: integer
      swapMemoryUsedPercent:
        type: number
      timeSinceUptime:
        type: string
      uptime:
        type: integer
    type: object
  dto.DiskInfo:
    properties:
      device:
        type: string
      free:
        type: integer
      inodesFree:
        type: integer
      inodesTotal:
        type: integer
      inodesUsed:
        type: integer
      inodesUsedPercent:
        type: number
      path:
        type: string
      total:
        type: integer
      type:
        type: string
      used:
        type: integer
      usedPercent:
        type: number
    type: object
  dto.GPUInfo:
    properties:
      fanSpeed:
        type: string
      gpuUtil:
        type: string
      index:
        type: integer
      maxPowerLimit:
        type: string
      memTotal:
        type: string
      memUsed:
        type: string
      memoryUsage:
        type: string
      performanceState:
        type: string
      powerDraw:
        type: string
      powerUsage:
        type: string
      productName:
        type: string
      temperature:
        type: string
    type: object
  dto.HostConnTest:
    properties:
      addr:
        type: string
      authMode:
        enum:
        - password
        - key
        type: string
      passPhrase:
        type: string
      password:
        type: string
      port:
        maximum: 65535
        minimum: 1
        type: integer
      privateKey:
        type: string
      user:
        type: string
    required:
    - addr
    - port
    - user
    type: object
  dto.HostOperate:
    properties:
      addr:
        type: string
      authMode:
        enum:
        - password
        - key
        type: string
      description:
        type: string
      groupID:
        type: integer
      id:
        type: integer
      name:
        type: string
      passPhrase:
        type: string
      password:
        type: string
      port:
        maximum: 65535
        minimum: 1
        type: integer
      privateKey:
        type: string
      rememberPassword:
        type: boolean
      user:
        type: string
    required:
    - addr
    - port
    - user
    type: object
  dto.Login:
    properties:
      authMethod:
        type: string
      captcha:
        type: string
      captchaID:
        type: string
      ignore_capycha:
        type: boolean
      name:
        type: string
      password:
        type: string
    type: object
  dto.OsInfo:
    properties:
      diskSize:
        type: integer
      kernelArch:
        type: string
      kernelVersion:
        type: string
      os:
        type: string
      platform:
        type: string
      platformFamily:
        type: string
    type: object
  dto.PageResult:
    properties:
      items: {}
      total:
        type: integer
    type: object
  dto.SSHHistory:
    properties:
      address:
        type: string
      area:
        type: string
      authMode:
        type: string
      date:
        type: string
      dateStr:
        type: string
      message:
        type: string
      port:
        type: string
      status:
        type: string
      user:
        type: string
    type: object
  dto.SSHLog:
    properties:
      failedCount:
        type: integer
      logs:
        items:
          $ref: '#/definitions/dto.SSHHistory'
        type: array
      successfulCount:
        type: integer
      totalCount:
        type: integer
    type: object
  dto.SearchLoginLogWithPage:
    properties:
      ip:
        type: string
      page:
        type: integer
      pageSize:
        type: integer
      status:
        type: string
    required:
    - page
    - pageSize
    type: object
  dto.SearchOpLogWithPage:
    properties:
      operation:
        type: string
      page:
        type: integer
      pageSize:
        type: integer
      source:
        type: string
      status:
        type: string
    required:
    - page
    - pageSize
    type: object
  dto.SearchSSHLog:
    properties:
      Status:
        enum:
        - Success
        - Failed
        - All
        type: string
      info:
        type: string
      page:
        type: integer
      pageSize:
        type: integer
    required:
    - Status
    - page
    - pageSize
    type: object
  dto.UserLoginInfo:
    properties:
      mfaStatus:
        type: string
      name:
        type: string
      token:
        type: string
    type: object
  request.FileReadByLineReq:
    properties:
      ID:
        type: integer
      latest:
        type: boolean
      name:
        type: string
      page:
        type: integer
      pageSize:
        type: integer
      type:
        type: string
    required:
    - page
    - pageSize
    - type
    type: object
host: localhost:8848
info:
  contact:
    email: support@yourwebapp.com
    name: API Support
  description: This is the API documentation for LinuxOnM.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: LinuxOnM API
  version: 1.0.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 安全入口 base64 加密串
        in: header
        name: EntranceCode
        required: true
        type: string
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.Login'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserLoginInfo'
      summary: User login
      tags:
      - Auth
  /dashboard/base/os:
    get:
      consumes:
      - application/json
      description: 获取服务器基础数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.OsInfo'
      security:
      - ApiKeyAuth: []
      summary: Load os info
      tags:
      - Dashboard
  /dashboard/current/:ioOption/:netOption:
    get:
      consumes:
      - application/json
      description: 获取首页实时数据
      parameters:
      - description: request
        in: path
        name: ioOption
        required: true
        type: string
      - description: request
        in: path
        name: netOption
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.DashboardCurrent'
      security:
      - ApiKeyAuth: []
      summary: Load dashboard current info
      tags:
      - Dashboard
  /file/read:
    post:
      description: 按行读取日志文件
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.FileReadByLineReq'
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Read file by Line
      tags:
      - File
  /host:
    post:
      consumes:
      - application/json
      description: This function is used to create or update a host. It first validates
        and binds the incoming JSON request data of type dto.HostOperate.
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.HostOperate'
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Create host
      tags:
      - Host
      x-panel-log:
        BeforeFunctions: []
        bodyKeys:
        - name
        - addr
        formatEN: create host [name][addr]
        formatZH: 创建主机 [name][addr]
        paramKeys: []
  /host/test/byid/:id:
    post:
      consumes:
      - application/json
      description: 测试主机连接
      parameters:
      - description: request
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      security:
      - ApiKeyAuth: []
      summary: Test host conn by host id
      tags:
      - Host
  /host/test/byinfo:
    post:
      consumes:
      - application/json
      description: This function is used to test the SSH connection to a host based
        on the connection information provided in the request body.
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.HostConnTest'
      responses:
        "200":
          description: Returns true if the SSH connection to the host is successfully
            established, false otherwise.
      security:
      - ApiKeyAuth: []
      summary: Test host connection by provided connection information
      tags:
      - Host
  /log/operation:
    post:
      consumes:
      - application/json
      description: 获取系统操作日志列表分页
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SearchOpLogWithPage'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PageResult'
      security:
      - ApiKeyAuth: []
      summary: Page operation logs
      tags:
      - Logs
  /log/ssh:
    post:
      consumes:
      - application/json
      description: 获取 SSH 登录日志
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SearchSSHLog'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SSHLog'
      security:
      - ApiKeyAuth: []
      summary: Load host SSH logs
      tags:
      - SSH
  /log/system/files:
    get:
      description: 获取系统日志文件列表
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Load system log files
      tags:
      - Logs
  /logs/login:
    post:
      consumes:
      - application/json
      description: 获取系统登录日志列表分页
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SearchLoginLogWithPage'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PageResult'
      security:
      - ApiKeyAuth: []
      summary: Page login logs
      tags:
      - Logs
swagger: "2.0"
